Add prettier formater
CodeYourFuture/project-quiz pull request #12
Opened 2020-04-01 22:32 UTC by kosenchiha

2020-04-02 16:43 UTC, bonboh requested changes
When testing this out, I realised we also need to add another file. Can you add the following JSON to this new file `.vscode/settings.json`?

```json
{
  "editor.formatOnSave": true
}
```

2020-04-02 16:43 UTC, bonboh commented on .prettierrc
> +  "jsxSingleQuote": true,
I just tried this out in VS Code and we should delete this line! `"jsxSingleQuote": true,`

2020-04-02 20:46 UTC, viktoriia-kosenko commented on .prettierrc
> +  "jsxSingleQuote": true,
Done!

2020-04-03 00:05 UTC, bonboh approved these changes
👍

2020-04-03 00:05 UTC, merged