Move the shuffle function from client side to the backend side
CodeYourFuture/project-quiz pull request #94
Opened 2020-07-14 09:58 UTC by abdulkadiret

2020-07-14 19:00 UTC, bonboh requested changes
Got a suggestion for making the shuffle function nicer to use from a dev perspective

2020-07-14 19:00 UTC, bonboh commented on routes/quizzes.js
> +    shuffle(quizQuestions);
```suggestion
    shuffle(quizQuestions);
```
It would be nice to be able to just call `shuffle` to shuffle the questions, without needing to know to do a `forEach` before. How about we move the `forEach` into `shuffle.js`?

2020-07-17 09:51 UTC, bonboh commented on routes/quizzes.js
> +    shuffle(quizQuestions);
@abdulkadiret We're moving line 11 to `shuffle.js`, so we would change `shuffle.js` to something like:

```
const shuffleQuestion = arr => {
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
};

const shuffle = quizQuestions =>
  quizQuestions.forEach(question => shuffleQuestion(question.answers));
```
This lets us pass in `quizQuestions` to the `shuffle` function and the function will shuffle everything for us. I haven't tested this code so please check that it works

2020-07-17 12:02 UTC, abdulkadiret commented on routes/quizzes.js
> +    shuffle(quizQuestions);
I changed the `shuffle.js` codes with above code and I removed line 11 from `routes/quizzes.js`. Unfortunately, it only shuffles the answers not the questions.

2020-07-21 08:42 UTC, bonboh approved these changes

2020-07-21 08:42 UTC, bonboh commented on routes/quizzes.js
> +    shuffle(quizQuestions);
Okay sure, thanks for giving it a go 👍

2020-07-21 08:42 UTC, merged